services:
    kv-storage:
        image: "valkey/valkey:8-alpine"

    hyperglass:
        build: .
        depends_on:
            - kv-storage
        environment:
            - HYPERGLASS_APP_PATH=/etc/hyperglass
            - HYPERGLASS_REDIS_HOST=${HYPERGLASS_REDIS_HOST-kv-storage}
            - HYPERGLASS_HOST=${HYPERGLASS_HOST-0.0.0.0}
            - HYPERGLASS_PORT=${HYPERGLASS_PORT-8001}
            - HYPERGLASS_DEBUG=${HYPERGLASS_DEBUG-false}
            - HYPERGLASS_DEV_MODE=${HYPERGLASS_DEV_MODE-false}
            - HYPEGLASS_DISABLE_UI=${HYPEGLASS_DISABLE_UI-false}
            - HYPERGLASS_CONTAINER=${HYPERGLASS_CONTAINER-true}
            - HYPERGLASS_ORIGINAL_APP_PATH=${HYPERGLASS_APP_PATH}
        ports:
            - "${HYPERGLASS_PORT-8001}:${HYPERGLASS_PORT-8001}"
        volumes:
            - ${HYPERGLASS_APP_PATH-/etc/hyperglass}:/etc/hyperglass
