{
 "title": "hyperglass",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_type", "label": "Query Type", "query": "label_values(type)" },
   { "name": "location", "label": "Location", "query": "label_values(loc_id)" },
   { "name": "source", "label": "Source IP", "query": "label_values(source)" },
   { "name": "target", "label": "Target", "query": "label_values(target)" }
  ]
 },
 "panels": [
  {
   "title": "Queries Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(count_data_total)" }
   ]
  },
  {
   "title": "Queries by Location",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_data_total) by (loc_id)",
     "legendFormat": "{{loc_id}}"
    }
   ]
  },
  {
   "title": "Queries by Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 7, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_data_total{type=\"bgp_route\"})",
     "legendFormat": "BGP Route"
    },
    {
     "expr": "sum(count_data_total{type=\"bgp_aspath\"})",
     "legendFormat": "BGP AS Path"
    },
    {
     "expr": "sum(count_data_total{type=\"bgp_community\"})",
     "legendFormat": "BGP Community"
    },
    {
     "expr": "sum(count_data_total{type=\"ping\"})",
     "legendFormat": "Ping"
    },
    {
     "expr": "sum(count_data_total{type=\"traceroute\"})",
     "legendFormat": "Traceroute"
    }
   ]
  },
  {
   "title": "Top 10 Query Targets",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum(count_data_total{target=~\"$target\"}) by (target))"
    }
   ]
  },
  {
   "title": "404 Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "sum(count_notfound_total)" }
   ]
  },
  {
   "title": "Rate Limit Exceeded: Query",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_ratelimit_total{message=\"429 Too Many Requests: Query\"})"
    }
   ]
  },
  {
   "title": "Rate Limit Exceeded: Site",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_ratelimit_total{message=\"429 Too Many Requests: Site\"})"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "count_data_total" }
   ]
  }
 ]
}